sources:
  - name: ajna
    handler:
      graphql:
        endpoint: "{context.url:https://api.thegraph.com/subgraphs/name/halaprix/gajna}"
    transforms:
      - autoPagination:
          validateSchema: true # Validates that the schema source actually contains the required input filters.
          limitOfRecords: 1000 # Default is 1000, you can change if you indexer has different configuration in GRAPH_GRAPHQL_MAX_FIRST var.
documents:
  - ./queries/weekly.graphql
  - ./queries/daily.graphql
  - ./queries/partnerRewardsDaily.graphql
  - ./queries/partnerRewardsWeekly.graphql
  - ./queries/pools.graphql
